// Build a single-file LocalDrop executable with the web UI embedded inside it.
//   1. Build the web UI (Vite)
//   2. Embed every file in web/dist into src/generated/webAssets.ts (base64)
//   3. Bundle the ESM server + web assets + deps into one CJS file (esbuild)
//   4. Package Node + bundle into one .exe (@yao-pkg/pkg)
//   5. Restore the empty webAssets stub so the working tree stays clean
import { execSync } from 'node:child_process';
import { build } from 'esbuild';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const serverDir = path.resolve(here, '..'); // apps/server
const repoRoot = path.resolve(serverDir, '..', '..'); // repo root
const webDir = path.resolve(serverDir, '..', 'web'); // apps/web
const assetsModule = path.join(serverDir, 'src', 'generated', 'webAssets.ts');

const STUB = `// Auto-generated by scripts/build-exe.mjs — the embedded web UI build.
// This committed version is an empty stub (used during dev, where the web UI
// is served by Vite). \`pnpm build:exe\` temporarily fills it with the base64
// of every file in apps/web/dist so the UI ships inside the executable.
export const webAssets: Record<string, string> = {};
`;

// Allow targeting another platform, e.g. `node build-exe.mjs node22-macos-x64`
const target = process.argv[2] || 'node22-win-x64';
const isWin = target.includes('win');
const outName = isWin ? 'LocalDrop.exe' : 'LocalDrop';

function run(cmd, cwd) {
  console.log(`\n$ ${cmd}`);
  execSync(cmd, { cwd, stdio: 'inherit' });
}

/** Recursively collect all files under a directory. */
function walk(dir, base = dir, out = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full, base, out);
    else out.push(full);
  }
  return out;
}

async function main() {
  // ── 1. Build the web UI via Vite's Node API ──
  // (The Vite CLI is intercepted by the Console Ninja editor extension in some
  //  shells and silently no-ops; the Node API is immune. We also clear dist
  //  first so stray `tsc` output never gets embedded.)
  const dist = path.join(webDir, 'dist');
  fs.rmSync(dist, { recursive: true, force: true });
  run(
    `node --input-type=module -e "import { build } from 'vite'; await build({ root: process.cwd() })"`,
    webDir,
  );
  if (!fs.existsSync(path.join(dist, 'index.html'))) {
    throw new Error('Vite build did not produce dist/index.html');
  }

  // ── 2. Embed web/dist into the generated assets module ──
  const files = walk(dist);
  const map = {};
  for (const file of files) {
    const key = '/' + path.relative(dist, file).split(path.sep).join('/');
    map[key] = fs.readFileSync(file).toString('base64');
  }
  const generated =
    '// AUTO-GENERATED — do not edit. Produced by scripts/build-exe.mjs.\n' +
    'export const webAssets: Record<string, string> = ' +
    JSON.stringify(map) +
    ';\n';
  fs.writeFileSync(assetsModule, generated);
  const totalKb = Math.round(
    Object.values(map).reduce((n, b64) => n + b64.length, 0) / 1024,
  );
  console.log(`✓ Embedded ${files.length} web files (~${totalKb}KB base64)`);

  // ── 3. Bundle the server (ESM -> single CJS file) ──
  const outfile = path.join(serverDir, 'build', 'server.cjs');
  fs.rmSync(path.join(serverDir, 'build'), { recursive: true, force: true });
  await build({
    entryPoints: [path.join(serverDir, 'src', 'index.ts')],
    bundle: true,
    platform: 'node',
    target: 'node22',
    format: 'cjs',
    outfile,
    // ws ships optional native speed-ups; it falls back to pure JS if absent.
    external: ['bufferutil', 'utf-8-validate'],
    logLevel: 'info',
  });
  console.log('✓ Bundled server -> build/server.cjs');

  // ── 4. Package into a single executable ──
  run(`pnpm exec pkg . --targets ${target} --output release/${outName}`, serverDir);

  console.log(`\n✅ Done: ${path.join(serverDir, 'release', outName)}`);
  console.log('   Double-click it to start LocalDrop — the browser opens automatically.');
}

main()
  .catch(err => {
    console.error(err);
    process.exitCode = 1;
  })
  .finally(() => {
    // Restore the empty stub so the embedded base64 never lands in git.
    fs.writeFileSync(assetsModule, STUB);
  });
